### ISSUE TITLE
Game crashing when exiting Windmill

### ISSUE THREAD

**Issue by rchrm5** [OoTRandomizer/OoT-Randomizer#1158]
This seed crashes each time the Windmill is exited as child (entered from playing Requiem of Spirit). I assume this has to do with the sandstorm actor that's supposed to load when entering Gerudo Fortress from Wasteland, as that was a problem in the past with Beta Quest, but not for certain.

[OoT_43A0A_3O9Y1ZA6WA_Spoiler.zip](https://github.com/TestRunnerSRL/OoT-Randomizer/files/5533121/OoT_43A0A_3O9Y1ZA6WA_Spoiler.zip)

Edit: Here are the error message screens from the Debugger in order:

Screen 1: "HungUp on Thread 4
RCP is HUNG UP!!"

Screen 2: "actor dlftbls 471
No. RamStart-RamEnd Offset
9 80240870-802416a0 006270b0
24 801dd530-801e1ef0 006a85d0
35 802416d0-802426a0 00654030
291 801e5df0-801e65a0 00897960
339 801e4da0-801e5af0 008dda10
465 801e2760-801e33a0 0099d100"

Screen 3: "CallBack (1) 800088a8 00000000 00000000"

**Comment by LostThePirate** [comment]
Just to clarify, what platform are you playing on? Are these Everdrive errors, or a specific Emu's errors?
You included your Spoiler Log, which contains which build this occurred on, but it's also helpful to include that in the GitHub issue.

**Comment by rchrm5** [comment]
I'm playing on Everdrive 64 X7. The crash results in the small yellow bar
in the upper left when playing, indicating a software issue. I'm guessing
this would be repeatable on emulator.

**Comment by flagrama** [comment]
Yeah, this is a known issue with the rando on hardware. Overworld Entrance Randomizer is really not recommended https://github.com/TestRunnerSRL/OoT-Randomizer/issues/915

**Comment by ETR-BTF** [comment]
Does this still crash or did the Sandstorm Transition Patch fix this?

**Comment by fenhl** [comment]
Since there have been no further reports of this since #1299, I'm going to assume that that PR fixed this. If this is encountered again in the future, please post a comment and we can reopen this issue.
