### ISSUE TITLE
Dungeon Entrance Hints Don't Appear On Gossip Stones in 6.0

### ISSUE THREAD

**Issue by 2dos** [OoTRandomizer/OoT-Randomizer#1220]
Using tournament hints and with dungeon entrance randomizer enabled, dungeon entrance hints no longer appear on gossip stones. This is different from the behavior from 5.2, which would generate 4 entrance hints with 2 copies. The JSON file in the tournament hint JSON indicates this was changed to show 4 entrance hints with 1 copy. Even forcing the hints to be always hints doesn't make them appear. Additionally, the other entrance hints seem to appear, such as grottos and the fairy fountains, when enabling grotto ER or interior entrance ER. 

ETR_BTF from the ZOOTR discord has indicated that the problem is possibly related to the following commit: https://github.com/TestRunnerSRL/OoT-Randomizer/pull/1124/commits/ee850eb7e5e9d27fbef7e2bbc12e1420c0e3ec9d

**Comment by fenhl** [comment]
This was fixed in #1237 and can be closed.
