### ISSUE TITLE
Inconsistent LW Gift from Saria behavior

### ISSUE THREAD

**Issue by fenhl** [OoTRandomizer/OoT-Randomizer#1228]
Starting a non-ocarina-shuffle seed with one or both ocarinas as starting items and entering the Lost Woods bridge from Kokiri Forest has different behavior depending on settings:

* If overworld ER is on, you end up with the Ocarina of Time.
* If overworld ER is off, you end up with the Fairy Ocarina, even if you started with the Ocarina of Time. The game displays the “you got the Fairy Ocarina” text box even if no item is actually obtained.

A quick and dirty fix would be to always enable the `OCARINAS_SHUFFLED` flag, but it doesn't look like the Ocarina of Time is a Bingo goal, so this is purely a visual bug except maybe in Freaky Fridays, so it might make sense to wait until a proper fix that preserves the cutscene is implemented.

This also raises further questions:

* What happens at the HF Ocarina of Time Item check if you already have the Ocarina of Time?
* What happens at the HF Ocarina of Time Item check if you don't have an ocarina?
* What happens at the LW Gift from Saria check if you didn't start with ocarinas but picked up the one from Hyrule Field first?

**Comment by flagrama** [comment]
> What happens at the HF Ocarina of Time Item check if you already have the Ocarina of Time?

You get another OoT because of how progressive items work. It is not a cutscene, just a normal get item location.
> What happens at the HF Ocarina of Time Item check if you don't have an ocarina?

You get a Fairy Ocarina because of how progressive items work. It is not a cutscene, just a normal get item location.
> What happens at the LW Gift from Saria check if you didn't start with ocarinas but picked up the one from Hyrule Field first?

For the cutscene version, you now have a Fairy Ocarina because the cutscene places an Fairy Ocarina, it is not a normal get item location. If not the cutscene version, you now have an Ocarina of Time because the non-cutscene version is a normal get item location.

**Comment by flagrama** [comment]
If ER actually affects how the cutscene works, it probably shouldn't.

**Comment by flagrama** [comment]
https://github.com/TestRunnerSRL/OoT-Randomizer/blob/a442b696c0dad14e11c4d6391eadaca7aabb0d19/Patches.py#L837-L841

Yeah, shuffled entrances always force enables shuffled ocarinas.

**Comment by r0bd0g** [comment]
ER affects the cutscene I guess b/c they didn't want to force the player to take the entrance on the other side of the bridge the first time the bridge is found, but also b/c it would take additional effort to make the cutscene take you to the correct location?

**Comment by Hamsda** [comment]
Yeah for a while during dev we got the ocarina on the bridge, even with ER off and ocarinas unshuffled, but people wanted the old style back, so now we have this weird setting dependent behavior.

**Comment by r0bd0g** [comment]
Getting the ocarina on the bridge was also buggy at the time; it left you in control in an alternate scene setup; weird actor placements and ability to use restricted items included.

**Comment by Hamsda** [comment]
Yeah, it's just a bit odd that we have this very inconsistent behavior now.

**Comment by fenhl** [comment]
So I think all that needs to change here is the cutscene version should check if you already have an ocarina, and in that case set the slot to the OoT instead of the fairy ocarina and use a different text box accordingly. The current patch for the cutscene is here, but I don't understand how it works: https://github.com/TestRunnerSRL/OoT-Randomizer/blob/6287282efa1040d2f35e00ab1cd37f829d0330c6/Patches.py#L550-L555
