### ISSUE TITLE
1 Dungeon Reward Rainbow Bridge redundant with Open Bridge

### ISSUE THREAD

**Issue by mracsys** [OoTRandomizer/OoT-Randomizer#1250]
Since the player always starts with one medallion or stone, rainbow bridge opening with one dungeon reward is functionally the same as the open bridge setting. Recommend a new minimum of 2 dungeon rewards when rainbow bridge set to dungeons.

**Comment by fenhl** [comment]
This would have to be reverted if/when med/stone shuffle is added but until then I guess it makes sense.

**Comment by fenhl** [comment]
Same thing for LACS btw.

**Comment by r0bd0g** [comment]
It's actually not fully redundant... Perhaps the player wants to watch the rainbow bridge spawn?

**Comment by fenhl** [comment]
I think that would make more sense for an “enable more/all cutscenes” setting.

**Comment by r0bd0g** [comment]
There is some relevance in rsl, if you visit castle before ToT, you can see the bridge or maybe you have to walk up to it and see if it spawns lol reaching a bit here.
