### ISSUE TITLE
Plando Shop Prices don't check for value

### ISSUE THREAD

**Issue by dotzo** [OoTRandomizer/OoT-Randomizer#1266]
This is basically a plethora of issues all having to do with user-defined prices of shop items in a plando file.  Nowhere in the code does the game ever check successfully that a shop item is below 1000 rupees, the only range of prices available to the player given the addition of the Tycoon wallet.  

We are also able to write any 2 byte value into the plando file and it will successfully generate, although with unexpected results as the game actually interprets this value as a signed integer, whereas the randomizer code interprets it as an unsigned integer.  As such, any value over 32767 will act as a negative value in-game and pass all the price checks, allowing you to buy them. However, even prices will drain your wallet entirely and odd prices will fill it, due to how the game does the math.

Additionally, the bogus values are written straight to the spoiler log without being updated.  Start of the investigation into plando'd shop items: https://discord.com/channels/274180765816848384/802659695323250729/817047845986893894. And the juicy bit where I start investigating large integers: https://discord.com/channels/274180765816848384/802659695323250729/817054743242866708

All testing was done on 6.0.36 f.LUM DEV.

**Comment by fenhl** [comment]
Sounds like this was fixed in #1267 and can be closed.
