### ISSUE TITLE
Presumably stepping into the Forest Temple blue warp again as child takes you to SFM instead of outside whereever Forest Temple is.

### ISSUE THREAD

**Issue by r0bd0g** [OoTRandomizer/OoT-Randomizer#1318]
This would allow you to potentially access child meadow when it would not normally be accessible.
Are there any other possible problems with child blue warps that maybe ought to be fixed?

**Comment by dewiniaid** [comment]
This is also true for Shadow Temple blue warp taking you to vanilla Shadow Temple entrance rather than where Shadow Temple is actually located.

**Comment by r0bd0g** [comment]
Yeah there my be other blue warps that also have issues. Forest I singled out b/c it can actually be done glitchless in certain settings.

**Comment by r0bd0g** [comment]
Any news on this? (I guess dungeon shortcuts might make it marginally more likely somebody does this, since it's possible that child will actually have to fight PG, and then maybe for some reason somebody comes back and steps in the warp again, idk.)

**Comment by fenhl** [comment]
Worth testing whether the changes made to blue warps on my fork fixed this.
