### ISSUE TITLE
Clearer Hints Text Needed

### ISSUE THREAD

**Issue by flagrama** [OoTRandomizer/OoT-Randomizer#1473]
Some hints don't have text for "Clearer Hints". Some of the more egregious ones in my opinion are the following:

- [ ] Rainbow Bridge requirement on the altar
- [ ] Ganon's Boss Key requirement on the altar
- [x] Song Location hints

Overall I think the https://github.com/TestRunnerSRL/OoT-Randomizer/blob/Dev/HintList.py needs another look and clearer hints should be provided for anything too cryptic. The vast majority of the list items have no "Clearer Hints" substitute.

**Comment by cjohnson57** [comment]
Auto closed by #2058, but only resolved one of the checkbox items

**Comment by r0bd0g** [comment]
I'm not sure what's confusing about the altar.

**Comment by alkalineace** [comment]
We got a lot of reports of people misunderstanding altar hints.
The light arrows image is misleading especially and should be removed.
The text is missing "rainbow bridge" to be completely clear.

One of the reports : https://discord.com/channels/274180765816848384/274186223147417600/1157300756165165066

**Comment by r0bd0g** [comment]
I guess, to be fair, you're probably supposed to know your bridge condition before you start. Is that based on some vanilla text? Is it possible that every box of that text needed an icon?
