### ISSUE TITLE
Epic Discount

### ISSUE THREAD

**Issue by r0bd0g** [OoTRandomizer/OoT-Randomizer#1565]
ETR_BTF — Today at 4:06 AM
elagatua buys a hylian shield at a "discount" and all their 92 rupees get drained from their wallet. is this a known vanilla bug?
https://clips.twitch.tv/BovineDaintyStingrayRuleFive-4q7vRdy3u34dehxS
cola pointed out that the rupee counter goes down in a strange way: the right digit stays the same while the left digit is decreasing

**Comment by fenhl** [comment]
Since this issue was only encountered once and #1857 has been merged since then, which may have fixed this, I'm going to close this issue. If this is encountered again in the future, please post a comment and we can reopen the issue.
