### ISSUE TITLE
Regional key shuffle doesn't account for dungeon entrance shuffle

### ISSUE THREAD

**Issue by JesseMaeder** [OoTRandomizer/OoT-Randomizer#1697]
The option to shuffle small/boss keys within a "region" surrounding and including the corresponding dungeon is very fun and interesting - however it doesn't account for dungeon entrance randomizer. For example, the Water Temple boss key will always be shuffled in the blue zone even if the dungeon at the Water Temple entrance is Spirit Temple.

**Comment by cjohnson57** [comment]
I believe this was a design decision.

**Comment by Jaybone25** [comment]
Yeah I believe it should remain how it is otherwise it spoils what dungeons are in specific entrances.   IE, you would know fire is in Shadow entrance before chasing down nocturne.

**Comment by ETR-BTF** [comment]
I think it'd also be weird to have it work like that when there's mixed pools (not in main yet, but it's important to take it into account nonetheless imo).

**Comment by fenhl** [comment]
I also believe this is working as intended.
