### ISSUE TITLE
Kokiri Tunic color weirdshot protection does not cover the entire crash range

### ISSUE THREAD

**Issue by ETR-BTF** [OoTRandomizer/OoT-Randomizer#1698]
It used to be thought that the crash would occur on "weird" weirdshot frames on all wads if the Green value of the Kokiri Tunic was over 0x98. To avoid the crashes, the randomizer would ban Green values over 0x98 when either Glitch Logic or No Logic was selected. However, recent developments suggest that this restriction would only help avoid crashes when the randomizer rom is injected into JP wads. It is believed that NA wads have their own range. Since the randomizer cannot possibly know which wad the rom will be injected into, all offending values should be avoided and not just the JP wad ones. Unfortunately, it is currently unknown what the offending values for NA wads are. These were determined for JP wads thru sheer testing. dotzo suspects that for NA wads it might be the byte formed by the 2nd nybble of Green and the first nybble of Blue, but hasn't done enough testing to be able to confidently confirm that hypothesis.

This was also discussed in #1686

**Comment by ETR-BTF** [comment]
Looks like it's a bit more complicated after all

> im here to complain about weirdshot crashes again lol, it looks like even with injecting into a jp wad, there can still be some crashes.  i got one today with #1598A5, and i repeated it to verify it was definitely the bad weirdshot frame that caused it

**Comment by fenhl** [comment]
Closing per https://github.com/OoTRandomizer/OoT-Randomizer/pull/1965#issuecomment-1741758607. If anyone is still experiencing the crash on seeds both generated and patched on randomizer versions 7.1.96 or newer, please leave a comment and we will reopen this issue.
