### ISSUE TITLE
Name not appearing in textbox.

### ISSUE THREAD

**Issue by teallen1996** [OoTRandomizer/OoT-Randomizer#208]
The name of my character did not appear in this textbox. It seems to only be that one that it occured with that I know of so far.

OoT Randomizer Version 2.20.26 f.LUM  -  Seed: GHWD4EDDXW

Settings (R82QA9MXKMAAN4DMXB):

![retroarch parallel n64 2 0-rc2 cf95ae0 07_10_2018 11_11_35 pm](https://user-images.githubusercontent.com/42753389/46587812-aad1b300-ca89-11e8-901c-5c5eb509402f.png)

**Comment by TestRunnerSRL** [comment]
I know I told you to post this, but for my own personal notes:
This is a problem that is generally specific to text shuffle. The solution to this should be either that if the text does co-op name does not exist then it reverts to the file name, or that there's some flag in rom to make it not use co-op names if single world

**Comment by fenhl** [comment]
An alternative solution could be moving the multiworld player names to a custom text component (from the system added in #1814) and remove the hacks for the vanilla player name component.

**Comment by fenhl** [comment]
I've implemented this fix on [my branch](https://github.com/fenhl/OoT-Randomizer) and can confirm that it works. Will PR as soon as #1814 is merged.
