### ISSUE TITLE
Get medallion repeatedly from Spirit Temple

### ISSUE THREAD

**Issue by r0bd0g** [OoTRandomizer/OoT-Randomizer#265]
If you step into the spirit blue warp again, you "get" the medallion again, rather than just being warped outside. This occurred in the most recent US weekly. I don't know if it also occurs on other dungeons, but I suspect if it does it might only be shadow temple?

**Comment by TestRunnerSRL** [comment]
I'm not sure how i'd fix this, and this seems really minor and doesn't really affect anything. They lose a few extra seconds watching the cutscene again. If someone wants to take a crack at it, go ahead.

**Comment by engineer124** [comment]
Worth noting that this behavior did have an impact when dungeon rewards were shuffled as this resulted in getting a item multiple times.

the branch `dev-fehnl` has a new blue warp implementation that now fixes this issue
