### ISSUE TITLE
If you already have the song that malon teaches, she won't give you the egg

### ISSUE THREAD

**Issue by r0bd0g** [OoTRandomizer/OoT-Randomizer#732]
Apparently this was a known issue with starting with items, but I didn't see it documented anywhere.
Apparently only occurs if song shuffle with items is not on.

**Comment by Roman971** [comment]
More specifically, it occurs only if `sons_as_items` is false (which is turned true by song shuffle but also "start with fast travel" among other cases).

**Comment by r0bd0g** [comment]
Was this ever fixed? I thought starting with songs automatically sets songs as items now? But maybe that's not enough to consider it fixed, exactly...

**Comment by flagrama** [comment]
Plando, which starting items uses in the background, should force this setting if you start with a song. So it should be fixed now. Would be good if someone could do some testing before we close this though.

**Comment by r0bd0g** [comment]
I wish songs as items weren't forced on for this though, and only the song checks with items would be changed... If somebody were to ever make that change, this bug with malon would still have to be fixed.

**Comment by flagrama** [comment]
You could probably conditionally apply the patches only for the songs that are items if you wanted to, but that's more of a feature/enhancement request than something to do with this bug :smile: 

I'm also not sure of a good way to check item locations for that conditional with information is available according to my debugger.

**Comment by fenhl** [comment]
So the bug occurs when there's a song on Malon of which a copy is also a starting item, am I understanding correctly?

**Comment by r0bd0g** [comment]
If you already have the song that Malon teaches at Lon Lon (it's not about starting items), she won't give you her item at Hyrule Castle.
But you also need songs_as_items to be false (as in, you have regular song cutscenes, as opposed to holding up music notes over your head).
I'm not sure if this is a possible situation anymore. Previously it was possible to encounter when using starting items.

**Comment by fenhl** [comment]
Starting with a song enables `songs_as_items`:
https://github.com/OoTRandomizer/OoT-Randomizer/blob/e9574b824c3da8c1ddd849cf977212baa4efc9ff/Patches.py#L358

So this is no longer possible.
