### ISSUE TITLE
Tektite Grotto PoH in Multiworld?

### ISSUE THREAD

**Issue by r0bd0g** [OoTRandomizer/OoT-Randomizer#848]
TrenteR_TR Today at 12:42 PM
Tektite Grotto in MW. If you collect the item it always shows as if the Item is for yourself, even if it's for someone else. (Only the Text does)

r0bd0g Today at 12:42 PM
Why only that item

TrenteR_TR Today at 12:43 PM
no idea
It always does it on that item
yesterday in the seed i did with friends. couple of weeks ago aswell

Apparently this is a seed that it happened in:
  ":version":         "4.13.21 f.LUM",
  "file_hash":        ["Bow", "Boss Key", "Slingshot", "Master Sword", "Slingshot"],
  ":seed":            "2BN8LDPKIT",
  ":settings_string": "CJWGC2XLHJAJFTQACTCTHBJTCLAABAJGD9JLAA",

He says he collects it with the iron boots on, if that matters.

**Comment by Roman971** [comment]
Could be related to the breath textbox which appears around the same time when you collect it with iron boots. Perhaps a name reset is triggered at the wrong time when the breath textbox is force closed in order for the item pickup textbox to display? 
Or this is much less likely but it could be trying to display both textboxes at around the same frames which may not work well..

**Comment by darkangel93x** [comment]
if you wear zora tunic this error doesn't happen.

**Comment by TestRunnerSRL** [comment]
This is essentially the same error as #208 but I'm not sure how i'd go about fixing it tbh

**Comment by fenhl** [comment]
Can confirm that my fix for #208 and #1854 also fixes this issue. Will PR as soon as #1814 is merged.
