### ISSUE TITLE
Speed up Master Sword cutscenes and Shadow boat

### ISSUE THREAD

**Issue by tommaniacal** [OoTRandomizer/OoT-Randomizer#922]
Is it possible to remove/shorten the mastersword cutscenes? 

Also, can we remove the Shadow Temple boat cutscene?

Is there a reason why the song of storms item check requires playing the ocarina, when most of the other song item checks don't require it?

**Comment by aofengen** [comment]
For the first two, yes it's possible to remove, but why? The MS custcene is 5-10 seconds at most, while the boat is about 30-40 seconds. These are about the only breaks left that you get during a run/race, and doing away with them doesn't gain very much in the end. "Gotta go fast" isn't a good enough reason.

As far as Song of Storms is concerned, it is different from the other songs. When songsanity was developed, the devs were unable to remove it like the rest. I'm not sure if the exact reason is known, but it was not feasible at the time.

**Comment by Cuphat** [comment]
Isn't removing the boat cutscene complicated by the fact that the boat actually moves during the cutscene?

**Comment by r0bd0g** [comment]
Yeah the boat it's like, the boat still has to move so you still have to wait the same time. I could see it allowing you to snag the gs on the way by maybe?? lol

**Comment by Nicholas-Steel** [comment]
Can the Song of Storms grotto openings be modified to react to putting the Ocarina to your lips (so long as you have the song) without having to play the actual song? Like how Quick Scarecrow currently works.

**Comment by tommaniacal** [comment]
> For the first two, yes it's possible to remove, but why? The MS custcene is 5-10 seconds at most, while the boat is about 30-40 seconds. These are about the only breaks left that you get during a run/race, and doing away with them doesn't gain very much in the end. "Gotta go fast" isn't a good enough reason.
> 
> As far as Song of Storms is concerned, it is different from the other songs. When songsanity was developed, the devs were unable to remove it like the rest. I'm not sure if the exact reason is known, but it was not feasible at the time.

Most people who are racing/running randomizer don't want breaks, they want to be in control of the game for as long as possible. Plus, if you're playing casually you'll end up going back and forth through time multiple times, so those 10 seconds add up quickly. I don't think having cutscene breaks is a good enough excuse to keep them in the game, when every other cutscene was removed for optimization

**Comment by aofengen** [comment]
Those breaks are some of the few opportunities left in a race where you can write things down or have a moment to plan out what you want to do next. I think they're highly valuable in that sense.

**Comment by Mast3rGenius** [comment]
> Those breaks are some of the few opportunities left in a race where you can write things down or have a moment to plan out what you want to do next. I think they're highly valuable in that sense.

Then why not make those cutscene skips off by default. I don't see much harm in adding the master sword cutscene skip at least.

**Comment by fenhl** [comment]
I realize it's been a while but I'm going through the list of open issues and PRs right now and updating things, and this issue is 3 feature requests in a trenchcoat. I'm going to repurpose this issue for the first two since they're at least both cutscene speed-ups, and those are generally something this project accepts, though the Shadow boat one would require some discussion on how exactly to handle it so it actually speeds things up, without interfering with the stalfos fight.

As for the 3rd one, anyone who still wants to see it is free to open a separate issue for it, but I think it's unlikely that that would be accepted since it would be a rather arbitrary removal of an item requirement for a check.

**Comment by r0bd0g** [comment]
I think what they meant by point three was that, the song of storms check you used to have to physically play song of storms when it's song as items, to get the check. That's been fixed for a while.

**Comment by Nicholas-Steel** [comment]
> I think what they meant by point three was that, the song of storms check you used to have to physically play song of storms when it's song as items, to get the check. That's been fixed for a while.

It's been too long, I no longer remember what I had meant lol. What you've said sounds most likely what I had meant.

**Comment by r0bd0g** [comment]
Oh I didn't see your suggestion. You wanted sos grottos to open immediately if you have song of storms and pull the ocarina, like how scarecrow immediately pops up on free scarecrow. A different suggestion from what op was suggesting.

**Comment by fenhl** [comment]
The Master Sword cutscene is being shortened in #2219.

**Comment by fenhl** [comment]
And the Shadow boat in #2239.
